name: import_sorter
description: Automatically sort all your flutter and dart imports
version: 1.0.0
homepage: "https://github.com/Matt-Gleich/import_sorter"
maintainer: Matthew Gleich (Matt-Gleich)
author: Matthew Gleich (Matt-Gleich)

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
