name: import_sorter
description: Dart package that automatically sort all your dart imports. Support for any dart project.
version: 1.0.10
homepage: 'https://github.com/Matt-Gleich/import_sorter'
maintainer: Matthew Gleich (@Matt-Gleich)
authors:
  - Flutter Community <community@flutter.zone>
  - Matthew Gleich <matthewgleich@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  yaml: ^2.2.0
  process_run: ^0.10.8

import_sorter:
  emojis: true
