name: import_sorter
description: Automatically organize your dart imports
version: 4.3.1
repository: 'https://github.com/Matt-Gleich/import_sorter'
homepage: 'https://mattglei.ch'
maintainer: Matthew Gleich (@Matt-Gleich)
authors:
  - Matthew Gleich <email@mattglei.ch>
  - Flutter Community <community@flutter.zone>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.6.0
  colorize: ^2.0.0
  yaml: ^2.2.1

dev_dependencies:
  test: ^1.15.5

import_sorter:
  emojis: true
