name: import_sorter
description: Dart package that automatically sort all your dart imports. Support for any dart project.
version: 1.0.5
homepage: 'https://github.com/Matt-Gleich/import_sorter'
maintainer: Matthew Gleich (Matt-Gleich)

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  yaml: ^2.2.0
